package troy.driver.schema

import troy.driver.CassandraDataType

/*
 * Represents the column's Cassandra data type
 * This type-class is meant to be instantiated at the call site (might be auto-generated by a macro/plugin)
 * to give the compiler a hint about the schema
 */
trait ColumnType[Version, Keyspace, Table, Column] {
  type Out <: CassandraDataType
}

object ColumnType {
  type Aux[Version, Keyspace, Table, Column, ColumnT] = ColumnType[Version, Keyspace, Table, Column] { type Out = ColumnT }

  def instance[Version, Keyspace, Table, Column, ColumnT <: CassandraDataType]: Aux[Version, Keyspace, Table, Column, ColumnT] =
    new ColumnType[Version, Keyspace, Table, Column] { type Out = ColumnT }
}
