/*
 * Copyright 2016 Tamer AbdulRadi
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package troy
package driver.schema

/**
 * V is expected to be a numric literal type
 * This type-class is meant to be instantiated at the call site (might be auto-generated by a macro/plugin)
 * to give the compiler a hint about the schema
 *
 * @author Tamer AbdulRadi
 */
trait VersionExists[V]

object VersionExists {
  def instance[V] = new VersionExists[V] {}
}

/**
 * V is expected to be a numric literal type
 * This type-class is meant to be instantiated at the call site (might be auto-generated by a macro/plugin)
 * to give the compiler a hint about the schema
 *
 * @author Tamer AbdulRadi
 */
trait LatestVersion[V]

object LatestVersion {
  def instance[V] = new LatestVersion[V] {}
}
