package troy.driver.schema.column

import troy.driver.schema.version.VersionExists

/*
 * Name is expected to be a textual literal type
 * This type-class is meant to be instantiated at the call site (might be auto-generated by a macro/plugin)
 * to give the compiler a hint about the schema
 */
trait ColumnExists[Version, Keyspace, Table, Name]

object ColumnExists {
  implicit def instance[V, K, T, Name](implicit ct: ColumnType[V, K, T, Name]) = new ColumnExists[V, K, T, Name] {}
}
