package troy.driver.schema.column

import troy.driver.CassandraDataType
import troy.driver.schema.table.TableExists

/*
 * Represents the column's Cassandra data type
 * This type-class is meant to be instantiated at the call site (might be auto-generated by a macro/plugin)
 * to give the compiler a hint about the schema
 */
trait ColumnType[Version, Keyspace, Table, Column] {
  type Out <: CassandraDataType
}

object ColumnType {
  type Aux[V, K, T, C, CT] = ColumnType[V, K, T, C] { type Out = CT }

  def instance[V, K, T, C, CT <: CassandraDataType](implicit tableExists: TableExists[V, K, T]): Aux[V, K, T, C, CT] =
    new ColumnType[V, K, T, C] { type Out = CT }
}
