package troy.driver.schema.keyspace

import troy.driver.schema.version.VersionExists

/*
 * Name is expected to be a textual literal type
 * This type-class is meant to be instantiated at the call site (might be auto-generated by a macro/plugin)
 * to give the compiler a hint about the schema
 */
trait KeyspaceExists[Version, Name]

object KeyspaceExists {
  def instance[Version: VersionExists, Name] = new KeyspaceExists[Version, Name] {}
}
