package troy.driver.schema.version

/*
 * V is expected to be a numric literal type
 * This type-class is meant to be instantiated at the call site (might be auto-generated by a macro/plugin)
 * to give the compiler a hint about the schema
 */
trait VersionExists[V]

object VersionExists {
  def instance[V] = new VersionExists[V] {}
}
